[tool.poetry]
name = "tezcanalyticx"
version = "0.0.1"
description = ""
authors = ["Ignacio Castillo <ignacio.bcastillo@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<=3.10"
option = "^2.1.0"
pymongo = "^4.6.3"
nanoid = "^2.0.0"
mictlanx = "^0.0.156"
pydantic = "^2.7.1"
pandas = "1.4.3"
seaborn = "^0.13.2"
# scipy = "^1.13.0"
scipy = "*"
fastapi = "^0.110.2"
uvicorn = "^0.29.0"


aiorwlock = "^1.4.0"
[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
more-itertools = "^10.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "test"
url = "https://test.pypi.org/simple/"
priority = "supplemental"